# Generated by Django 3.0 on 2020-04-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('num_seasons', models.IntegerField(blank=True, null=True)),
                ('descr', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.URLField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ostes.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('descr', models.CharField(blank=True, max_length=2000, null=True)),
                ('num_episodes', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Movie')),
            ],
            options={
                'managed': True,
                'unique_together': {('id', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='music/%Y/%m/%d/')),
                ('ost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.OST')),
            ],
            options={
                'managed': True,
                'unique_together': {('id', 'ost')},
            },
        ),
        migrations.CreateModel(
            name='MoviehasCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Category')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Movie')),
            ],
            options={
                'managed': True,
                'unique_together': {('category', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(through='ostes.MoviehasCategories', to='ostes.Category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ostes.OST'),
        ),
        migrations.CreateModel(
            name='EpisodeMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Episode')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Music')),
            ],
            options={
                'managed': True,
                'unique_together': {('music', 'episode')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='music',
            field=models.ManyToManyField(through='ostes.EpisodeMusic', to='ostes.Music'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostes.Season'),
        ),
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(through='ostes.MoviehasCategories', to='ostes.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('name', 'ost')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('id', 'season')},
        ),
    ]
