# Generated by Django 3.0 on 2020-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ost',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='ost',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
